Repository vslee/IEXSharp, pull requests merged in 2020-05, with the labels that each got.

#21 Enum descriptors and using .getDescription()
  IEXSharp/Helper/EnumExtension.cs
  IEXSharp/Model/Account/Request/UsageType.cs
  IEXSharp/Model/ReferenceData/Request/DateType.cs
  IEXSharp/Model/ReferenceData/Request/DirectionType.cs
  IEXSharp/Model/Stock/Request/BatchType.cs
  IEXSharp/Model/Stock/Request/CollectionType.cs
  IEXSharp/Model/Stock/Request/IPOType.cs
  IEXSharp/Model/Stock/Request/UpcomingEventType.cs
  IEXSharp/Model/StockFundamentals/Request/DividendRange.cs
  IEXSharp/Model/StockFundamentals/Request/Period.cs
  IEXSharp/Model/StockFundamentals/Request/SplitRange.cs
  IEXSharp/Model/StockPrices/Request/ChartRange.cs
  IEXSharp/Service/V1/Stock/IStockService.cs
  IEXSharp/Service/V1/Stock/StockService.cs
  IEXSharp/Service/V2/Account/AccountService.cs
  IEXSharp/Service/V2/ReferenceData/ReferenceDataService.cs
  IEXSharp/Service/V2/Stock/StockService.cs
  IEXSharp/Service/V2/StockFundamentals/IStockFundamentalsService.cs
  IEXSharp/Service/V2/StockFundamentals/StockFundamentalsService.cs
  IEXSharp/Service/V2/StockPrices/IStockPricesService.cs
  IEXSharp/Service/V2/StockPrices/StockPricesService.cs
  IEXSharpTest/Cloud(V2)/StockFundamentalsTest.cs
  IEXSharpTest/Cloud(V2)/StockPricesTest.cs
  IEXSharpTest/Helper/EnumExtensionTest.cs
  IEXSharpTest/V1/StockTest.cs
Labels: maintenance

#22 Preventitive measures for thread blocking
  IEXSharp/Helper/ExecutorREST.cs
Labels: maintenance

#23 Add OptionsService
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/Options/Request/OptionSide.cs
  IEXSharp/Model/Options/Response/OptionResponse.cs
  IEXSharp/Service/Cloud/Options/IOptionsService.cs
  IEXSharp/Service/Cloud/Options/OptionsService.cs
  IEXSharpTest/Cloud/OptionsTest.cs
Labels: enhancement

#24 MarketInfo Refactoring
  IEXSharp/Model/MarketInfo/Request/ListType.cs
  IEXSharp/Service/Cloud/MarketInfo/IMarketInfoService.cs
  IEXSharp/Service/Cloud/MarketInfo/MarketInfoService.cs
  IEXSharpTest/Cloud/MarketInfoTest.cs
Labels: enhancement

#25 Add Analyst Recommendations
  IEXSharp/Model/StockResearch/Response/AnalystRecommendationsResponse.cs
  IEXSharp/Service/Cloud/StockResearch/IStockResearchService.cs
  IEXSharp/Service/Cloud/StockResearch/StockResearchService.cs
  IEXSharpTest/Cloud/StockResearchTest.cs
Labels: enhancement

#26 MarketInfo event rework
  IEXSharp/Model/MarketInfo/Response/IPOCalendarResponse.cs
  IEXSharp/Model/MarketInfo/Response/UpcomingEarningsResponse.cs
  IEXSharp/Model/MarketInfo/Response/UpcomingEventResponse.cs
  IEXSharp/Model/Stock/Response/IPOCalendar.cs
  IEXSharp/Model/StockFundamentals/Response/Split.cs
  IEXSharp/Service/Cloud/MarketInfo/IMarketInfoService.cs
  IEXSharp/Service/Cloud/MarketInfo/MarketInfoService.cs
  IEXSharp/Service/Legacy/Stock/IStockService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Cloud/MarketInfoTest.cs
Labels: maintenance

#27 Removed Effective Spread Endpoint
  IEXSharp/Service/Cloud/Stock/IStockService.cs
  IEXSharp/Service/Cloud/Stock/StockService.cs
  IEXSharpTest/Cloud/StockPricesTest.cs
  IEXSharpTest/Cloud/StockTest.cs
Labels: maintenance

#28 Tests, typos and restructuring
  IEXSharp/Service/Cloud/InvestorsExchangeData/IInvestorsExchangeDataService.cs
  IEXSharp/Service/Cloud/InvestorsExchangeData/InvestorsExchangeDataService.cs
  IEXSharp/Service/Legacy/Market/IMarketService.cs
  IEXSharp/Service/Legacy/Market/MarketService.cs
  IEXSharpTest/Cloud/APISystemMetadataTest.cs
  IEXSharpTest/Cloud/AccountTest.cs
  IEXSharpTest/Cloud/AlternativeDataTest.cs
  IEXSharpTest/Cloud/CorporateActionsTest.cs
  IEXSharpTest/Cloud/CryptoTest.cs
  IEXSharpTest/Cloud/ForexCurrenciesTest.cs
  IEXSharpTest/Cloud/InvestorsExchangeDataTest.cs
  IEXSharpTest/Cloud/MarketInfoTest.cs
  IEXSharpTest/Cloud/OptionsTest.cs
  IEXSharpTest/Cloud/ReferenceDataTest.cs
  IEXSharpTest/Cloud/SSETest.cs
  IEXSharpTest/Cloud/StockFundamentalsTest.cs
  IEXSharpTest/Cloud/StockPricesTest.cs
  IEXSharpTest/Cloud/StockProfilesTest.cs
  IEXSharpTest/Cloud/StockResearchTest.cs
  IEXSharpTest/Cloud/StockTest.cs
  IEXSharpTest/Cloud/TestGlobal.cs
  IEXSharpTest/Legacy/MarketTest.cs
  IEXSharpTest/Legacy/ReferenceDataTest.cs
  IEXSharpTest/Legacy/StatsTest.cs
  IEXSharpTest/Legacy/StockTest.cs
Labels: maintenance

#29 Adding CEO Compensation, Social Sentiment, and Treasuries Services
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/IEXCloudClient.cs
  IEXSharp/IEXSharp.csproj
  IEXSharp/Model/CeoCompensation/Response/CeoCompensationResponse.cs
  IEXSharp/Model/SocialSentiment/Response/SentimentMinuteResponse.cs
  IEXSharp/Model/SocialSentiment/Response/SentimentResponse.cs
  IEXSharp/Model/Treasuries/Request/TreasuryRateSymbol.cs
  IEXSharp/Model/Treasuries/Response/TreasuryResponse.cs
  IEXSharp/Service/Cloud/CeoCompensation/CeoCompensationService.cs
  IEXSharp/Service/Cloud/CeoCompensation/ICeoCompensationService.cs
  IEXSharp/Service/Cloud/SocialSentiment/ISocialSentimentService.cs
  IEXSharp/Service/Cloud/SocialSentiment/SocialSentimentService.cs
  IEXSharp/Service/Cloud/Treasuries/ITreasuriesService.cs
  IEXSharp/Service/Cloud/Treasuries/TreasuriesService.cs
  IEXSharpTest/Cloud/CeoCompensationTest.cs
  IEXSharpTest/Cloud/SocialSentimentTest.cs
  IEXSharpTest/Cloud/TreasuriesTest.cs
Labels: enhancement

#31 Added GetEnumFromDescription<TEnum>() extension method
  IEXSharp/Helper/StringExtensions.cs
  IEXSharp/Model/Stock/Request/BatchType.cs
  IEXSharp/Model/StockPrices/Request/ChartRange.cs
  IEXSharpTest/Helper/StringExtensionsTest.cs
Labels: enhancement

#32 Added NewsService and methods
  IEXSharp/IEXCloudClient.cs
  IEXSharp/IEXSharp.csproj
  IEXSharp/Model/News/Response/HistoricalNewResponse.cs
  IEXSharp/Model/News/Response/NewsLegacy.cs
  IEXSharp/Model/News/Response/NewsResponse.cs
  IEXSharp/Model/Shared/Response/News.cs
  IEXSharp/Model/Stock/Response/BatchBySymbolLegacyResponse.cs
  IEXSharp/Model/Stock/Response/BatchResponse.cs
  IEXSharp/Model/Stock/Response/NewsResponse.cs
  IEXSharp/Service/Cloud/News/INewsService.cs
  IEXSharp/Service/Cloud/News/NewsService.cs
  IEXSharp/Service/Cloud/Stock/IStockService.cs
  IEXSharp/Service/Cloud/Stock/StockService.cs
  IEXSharp/Service/Legacy/Stock/IStockService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Cloud/NewsTests.cs
  IEXSharpTest/Cloud/StockTest.cs
  IEXSharpTest/Helper/StringExtensionsTest.cs
Labels: enhancement

#33 Adding Commodities Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/IEXSharp.csproj
  IEXSharp/Model/Commodities/Request/CommoditySymbol.cs
  IEXSharp/Model/Shared/Response/TimeSeriesResponse.cs
  IEXSharp/Model/Stock/Response/BatchResponse.cs
  IEXSharp/Model/Stock/Response/RecommendationTrendResponse.cs
  IEXSharp/Service/Cloud/Commodities/CommoditiesService.cs
  IEXSharp/Service/Cloud/Commodities/ICommoditiesService.cs
  IEXSharp/Service/Cloud/News/NewsService.cs
  IEXSharp/Service/Cloud/SocialSentiment/ISocialSentimentService.cs
  IEXSharp/Service/Cloud/SocialSentiment/SocialSentimentService.cs
  IEXSharp/Service/Cloud/Treasuries/ITreasuriesService.cs
  IEXSharp/Service/Cloud/Treasuries/TreasuriesService.cs
  IEXSharpTest/Cloud/CommoditiesTest.cs
  IEXSharpTest/Cloud/SocialSentimentTest.cs
Labels: enhancement

#34 Adding Economic Data Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/EconomicData/Request/EconomicDataSymbol.cs
  IEXSharp/Model/EconomicData/Request/EconomicDataTimeSeriesSymbol.cs
  IEXSharp/Model/News/Response/HistoricalNewResponse.cs
  IEXSharp/Model/Shared/Response/TimeSeriesResponse.cs
  IEXSharp/Service/Cloud/EconomicData/EconomicDataService.cs
  IEXSharp/Service/Cloud/EconomicData/IEconomicDataService.cs
  IEXSharpTest/Cloud/EconomicDataTest.cs
Labels: enhancement

#35 Namespace and Imports Cleanup
  IEXSharp/Helper/ExecutorBase.cs
  IEXSharp/Helper/ExecutorSSE.cs
  IEXSharp/Helper/SSEClient.cs
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/Commodities/Request/CommoditySymbol.cs
  IEXSharp/Model/Crypto/Response/CryptoBookQuote.cs
  IEXSharp/Model/Crypto/Response/CryptoBookResponse.cs
  IEXSharp/Model/Crypto/Response/CryptoPriceResponse.cs
  IEXSharp/Model/Crypto/Response/QuoteCryptoResponse.cs
  IEXSharp/Model/IEXResponse.cs
  IEXSharp/Model/MarketInfo/Response/IPOCalendarResponse.cs
  IEXSharp/Model/News/Response/NewsResponse.cs
  IEXSharp/Model/Options/Response/OptionResponse.cs
  IEXSharp/Model/ReferenceData/Response/IEXCorporateActionsResponse.cs
  IEXSharp/Model/ReferenceData/Response/SearchResponse.cs
  IEXSharp/Model/Shared/Response/EventCrypto.cs
  IEXSharp/Model/Shared/Response/QuoteSSE.cs
  IEXSharp/Model/Shared/Response/TimeSeriesResponse.cs
  IEXSharp/Model/Stock/Request/BatchType.cs
  IEXSharp/Model/Stock/Request/StockQuoteSSEInterval.cs
  IEXSharp/Model/Stock/Response/BatchBySymbolLegacyResponse.cs
  IEXSharp/Model/StockPrices/Request/ChartRange.cs
  IEXSharp/Model/StockResearch/Response/AnalystRecommendationsResponse.cs
  IEXSharp/Service/Cloud/CeoCompensation/CeoCompensationService.cs
  IEXSharp/Service/Cloud/CeoCompensation/ICeoCompensationService.cs
  IEXSharp/Service/Cloud/Commodities/CommoditiesService.cs
  IEXSharp/Service/Cloud/Commodities/ICommoditiesService.cs
  IEXSharp/Service/Cloud/Crypto/CryptoService.cs
  IEXSharp/Service/Cloud/Crypto/ICryptoService.cs
  IEXSharp/Service/Cloud/EconomicData/EconomicDataService.cs
  IEXSharp/Service/Cloud/ForexCurrencies/IForexCurrenciesService.cs
  IEXSharp/Service/Cloud/News/INewsService.cs
  IEXSharp/Service/Cloud/News/NewsService.cs
  IEXSharp/Service/Cloud/SSE/ISSEService.cs
  IEXSharp/Service/Cloud/SSE/SSEService.cs
  IEXSharp/Service/Cloud/SocialSentiment/ISocialSentimentService.cs
  IEXSharp/Service/Cloud/SocialSentiment/SocialSentimentService.cs
  IEXSharp/Service/Cloud/StockFundamentals/IStockFundamentalsService.cs
  IEXSharp/Service/Cloud/StockPrices/IStockPricesService.cs
  IEXSharp/Service/Cloud/StockProfiles/IStockProfilesService.cs
  IEXSharp/Service/Cloud/StockProfiles/StockProfilesService.cs
  IEXSharp/Service/Cloud/StockResearch/IStockResearchService.cs
  IEXSharp/Service/Cloud/StockResearch/StockResearchService.cs
  IEXSharp/Service/Cloud/Treasuries/ITreasuriesService.cs
  IEXSharp/Service/Cloud/Treasuries/TreasuriesService.cs
  IEXSharp/Service/Legacy/Market/IMarketService.cs
  IEXSharp/Service/Legacy/Market/MarketService.cs
  IEXSharpTest/Cloud/CommoditiesTest.cs
  IEXSharpTest/Cloud/NewsTests.cs
Labels: maintenance

#36 Add Option Symbols to ReferenceDataService
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Service/Cloud/ReferenceData/IReferenceDataService.cs
  IEXSharp/Service/Cloud/ReferenceData/ReferenceDataService.cs
  IEXSharpTest/Cloud/ReferenceDataTest.cs
Labels: enhancement

#38 Fixing issues with Dividend (Basic) functionality
  IEXSharp/Model/Shared/Request/Period.cs
  IEXSharp/Model/Shared/Response/Dividend.cs
  IEXSharp/Service/Cloud/MarketInfo/IMarketInfoService.cs
  IEXSharp/Service/Cloud/MarketInfo/MarketInfoService.cs
  IEXSharp/Service/Cloud/StockFundamentals/IStockFundamentalsService.cs
  IEXSharp/Service/Cloud/StockFundamentals/StockFundamentalsService.cs
  IEXSharp/Service/Cloud/StockResearch/IStockResearchService.cs
  IEXSharp/Service/Cloud/StockResearch/StockResearchService.cs
  IEXSharp/Service/Legacy/Stock/IStockService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Cloud/MarketInfoTest.cs
  IEXSharpTest/Cloud/StockFundamentalsTest.cs
  IEXSharpTest/Cloud/StockResearchTest.cs
Labels: enhancement

#39 Legacy Test Ignoring
  IEXSharp/Helper/DateTimeExtensions.cs
  IEXSharp/Model/Stock/Response/ChartLegacyResponse.cs
  IEXSharp/Service/Legacy/Stats/StatsService.cs
  IEXSharp/Service/Legacy/Stock/IStockService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Helper/DateTimeExtensionsTest.cs
  IEXSharpTest/Legacy/MarketTest.cs
  IEXSharpTest/Legacy/ReferenceDataTest.cs
  IEXSharpTest/Legacy/StockTest.cs
Labels: maintenance

#41 handle empty Split/Dividend result w/ Next param
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Service/Cloud/StockFundamentals/StockFundamentalsService.cs
  IEXSharpTest/Cloud/StockFundamentalsTest.cs
Labels: bug

#42 simplify Split/Dividend special case fix
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Service/Cloud/StockFundamentals/StockFundamentalsService.cs
Labels: maintenance

#43 More fixes for "Next" edge cases
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Service/Cloud/CorporateActions/CorporateActionsService.cs
  IEXSharp/Service/Cloud/CorporateActions/ICorporateActionsService.cs
  IEXSharpTest/Cloud/BatchTest.cs
  IEXSharpTest/Cloud/CorporateActionsTest.cs
  IEXSharpTest/Cloud/ReferenceDataTest.cs
Labels: bug

#44 Align reportDate type in Income Statement with CashFlow and BalanceSheet
  IEXSharp/Model/StockFundamentals/Response/IncomeStatementResponse.cs
  IEXSharpTest/Cloud/StockFundamentalsTest.cs
Labels: maintenance

#45 Including additional Chart Range options
  IEXSharp/Model/StockPrices/Request/ChartRange.cs
Labels: enhancement

#46 Make UnitTests fail when there is a new Json value in the REST reponse not being parsed
  IEXSharp/Assembly.cs
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/IEXCloudClient.cs
  IEXSharp/IEXLegacyClient.cs
  IEXSharp/Model/MarketInfo/Response/IPOCalendarResponse.cs
  IEXSharp/Model/MarketInfo/Response/UpcomingEarningEvent.cs
  IEXSharp/Model/MarketInfo/Response/UpcomingEventResponse.cs
  IEXSharp/Model/ReferenceData/Response/ExchangeInternationalResponse.cs
  IEXSharp/Model/ReferenceData/Response/ExchangeUSResponse.cs
  IEXSharp/Model/ReferenceData/Response/SymbolInternationalResponse.cs
  IEXSharp/Model/ReferenceData/Response/SymbolMutualFundResponse.cs
  IEXSharp/Model/ReferenceData/Response/SymbolResponse.cs
  IEXSharp/Model/Shared/Response/CashFlow.cs
  IEXSharp/Model/Shared/Response/Dividend.cs
  IEXSharp/Model/Shared/Response/Earning.cs
  IEXSharp/Model/Shared/Response/Financial.cs
  IEXSharp/Model/Shared/Response/Pair.cs
  IEXSharp/Model/Shared/Response/Quote.cs
  IEXSharp/Model/StockFundamentals/Response/BalanceSheetResponse.cs
  IEXSharp/Model/StockFundamentals/Response/DividendResponse.cs
  IEXSharp/Model/StockFundamentals/Response/EarningTodayResponse.cs
  IEXSharp/Model/StockFundamentals/Response/IncomeStatementResponse.cs
  IEXSharp/Model/StockFundamentals/Response/Split.cs
  IEXSharp/Service/Cloud/APISystemMetadata/APISystemMetadata.cs
  IEXSharp/Service/Cloud/Account/AccountService.cs
  IEXSharp/Service/Cloud/Batch/BatchService.cs
  IEXSharp/Service/Cloud/CeoCompensation/CeoCompensationService.cs
  IEXSharp/Service/Cloud/Commodities/CommoditiesService.cs
  IEXSharp/Service/Cloud/CorporateActions/CorporateActionsService.cs
  IEXSharp/Service/Cloud/Crypto/CryptoService.cs
  IEXSharp/Service/Cloud/EconomicData/EconomicDataService.cs
  IEXSharp/Service/Cloud/ForexCurrencies/ForexCurrenciesService.cs
  IEXSharp/Service/Cloud/InvestorsExchangeData/InvestorsExchangeDataService.cs
  IEXSharp/Service/Cloud/MarketInfo/IMarketInfoService.cs
  IEXSharp/Service/Cloud/MarketInfo/MarketInfoService.cs
  IEXSharp/Service/Cloud/News/NewsService.cs
  IEXSharp/Service/Cloud/Options/OptionsService.cs
  IEXSharp/Service/Cloud/ReferenceData/ReferenceDataService.cs
  IEXSharp/Service/Cloud/SocialSentiment/SocialSentimentService.cs
  IEXSharp/Service/Cloud/StockFundamentals/StockFundamentalsService.cs
  IEXSharp/Service/Cloud/StockPrices/StockPricesService.cs
  IEXSharp/Service/Cloud/StockProfiles/StockProfilesService.cs
  IEXSharp/Service/Cloud/StockResearch/StockResearchService.cs
  IEXSharp/Service/Cloud/Treasuries/TreasuriesService.cs
  IEXSharp/Service/Legacy/Market/MarketService.cs
  IEXSharp/Service/Legacy/ReferenceData/ReferenceDataService.cs
  IEXSharp/Service/Legacy/Stats/StatsService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Cloud/MarketInfoTest.cs
  IEXSharpTest/Cloud/ReferenceDataTest.cs
  IEXSharpTest/Cloud/StockFundamentalsTest.cs
  IEXSharpTest/Helper/IEXCloudClientForTest.cs
Labels: maintenance

#48 Use Exponential Back-Off strategy when a 429 Http code is returned
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/IEXSharp.csproj
  IEXSharpTest/Cloud/ExecutorRESTTest.cs
Labels: enhancement

#49 Premium Data - Wall Street Horizon
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/BoardOfDirectorsMeetingResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/BuybacksResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/FdaAdvisoryCommiteeMeetingsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/FilingsDueDatesResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/FiscalQuarterEndResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/HolidaysResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/IndexChangesResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/IposResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/LegalActionsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/ProductEventsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/SameStoreSalesResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/SecondaryOfferingsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/ShareHolderMeetingsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/WallStreetHorizonEventResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/WallStreetHorizonResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/WitchingHourResponse.cs
  IEXSharp/Service/Cloud/APISystemMetadata/APISystemMetadata.cs
  IEXSharp/Service/Cloud/Account/AccountService.cs
  IEXSharp/Service/Cloud/PremiumData/WallStreetHorizon/IWallStreetHorizonService.cs
  IEXSharp/Service/Cloud/PremiumData/WallStreetHorizon/WallStreetHorizonService.cs
  IEXSharp/Service/Legacy/Market/MarketService.cs
  IEXSharp/Service/Legacy/ReferenceData/ReferenceDataService.cs
  IEXSharp/Service/Legacy/Stats/StatsService.cs
  IEXSharp/Service/Legacy/Stock/StockService.cs
  IEXSharpTest/Cloud/CoreData/InvestorsExchangeDataTest.cs
  IEXSharpTest/Cloud/ExecutorRESTTest.cs
  IEXSharpTest/Cloud/PremiumData/WallStreetHorizonTest.cs
Labels: enhancement

#50 Wall Street Horizon Tests and Share Holder Meetings
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/CompanyTravelResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/HolidaysResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/LegalActionsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/MergersAndAcquisitionsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/ShareHolderMeetingsResponse.cs
  IEXSharp/Model/PremiumData/WallStreetHorizon/Response/WallStreetHorizonEventResponse.cs
  IEXSharp/Service/Cloud/PremiumData/WallStreetHorizon/IWallStreetHorizonService.cs
  IEXSharp/Service/Cloud/PremiumData/WallStreetHorizon/WallStreetHorizonService.cs
  IEXSharpTest/Cloud/PremiumData/WallStreetHorizonTest.cs
Labels: bug

#51 Fraud Factors Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/FraudFactors/Response/NonTimelyFilingsResponse.cs
  IEXSharp/Model/PremiumData/FraudFactors/Response/SimiliarityIndexResponse.cs
  IEXSharp/Service/Cloud/CoreData/ForexCurrencies/IForexCurrenciesService.cs
  IEXSharp/Service/Cloud/PremiumData/FraudFactors/FraudFactorsService.cs
  IEXSharp/Service/Cloud/PremiumData/FraudFactors/IFraudFactorsService.cs
  IEXSharp/Service/Cloud/PremiumData/WallStreetHorizon/IWallStreetHorizonService.cs
  IEXSharpTest/Cloud/PremiumData/FraudFactorsTest.cs
Labels: enhancement

#52 ExtractAlpha Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/CrossAssetModelOneResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgCpscComplaintsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgCpscRecallsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgDolVisaApplicationsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgEpaEnforcementsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgEpaMilestonesResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgFecIndividualCampaignContributionsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgOshaInspectionsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgSenateLobbyingResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgUsaSpendingResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgUsptoPatentApplicationsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/EsgUsptoPatentGrantsResponse.cs
  IEXSharp/Model/PremiumData/ExtractAlpha/Response/TacticalModelOneResponse.cs
  IEXSharp/Service/Cloud/PremiumData/ExtractAlpha/ExtractAlphaService.cs
  IEXSharp/Service/Cloud/PremiumData/ExtractAlpha/IExtractAlphaService.cs
  IEXSharpTest/Cloud/PremiumData/ExtractAlphaTest.cs
Labels: enhancement

#54 Kavout Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/Kavout/Response/KavoutResponse.cs
  IEXSharp/Service/Cloud/PremiumData/ExtractAlpha/IExtractAlphaService.cs
  IEXSharp/Service/Cloud/PremiumData/Kavout/IKavoutService.cs
  IEXSharp/Service/Cloud/PremiumData/Kavout/KavoutService.cs
  IEXSharpTest/Cloud/PremiumData/KavoutTest.cs
Labels: enhancement

#53 Precision Alpha Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/PrecisionAlpha/Response/PriceDynamicsResponse.cs
  IEXSharp/Service/Cloud/PremiumData/PrecisionAlpha/IPrecisionAlphaService.cs
  IEXSharp/Service/Cloud/PremiumData/PrecisionAlpha/PrecisionAlphaService.cs
  IEXSharpTest/Cloud/PremiumData/PrecisionAlphaTest.cs
Labels: enhancement

#55 AuditAnalytics Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/AuditAnalytics/Response/AccountingQualityAndRiskMatrixResponse.cs
  IEXSharp/Model/PremiumData/AuditAnalytics/Response/DirectorAndOfficerChangesResponse.cs
  IEXSharp/Service/Cloud/PremiumData/AuditAnalytics/AuditAnalyticsService.cs
  IEXSharp/Service/Cloud/PremiumData/AuditAnalytics/IAuditAnalyticsService.cs
  IEXSharpTest/Cloud/PremiumData/AuditAnalyticsTest.cs
Labels: enhancement

#57 Bugfix - PriceTargetResponse missing currency property
  IEXSharp/Model/CoreData/StockResearch/Response/PriceTargetResponse.cs
Labels: bug

#56 BRAIN Company Service
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/PremiumData/BrainCompany/Response/DifferencesInLanguageMetricsOnCompanyFilingsResponse.cs
  IEXSharp/Model/PremiumData/BrainCompany/Response/EstimatedReturnRankingResponse.cs
  IEXSharp/Model/PremiumData/BrainCompany/Response/LanguageMetricsOnCompanyFilingsResponse.cs
  IEXSharp/Model/PremiumData/BrainCompany/Response/SentimentIndicatorResponse.cs
  IEXSharp/Service/Cloud/PremiumData/BrainCompany/BrainCompanyService.cs
  IEXSharp/Service/Cloud/PremiumData/BrainCompany/IBrainCompany.cs
  IEXSharp/Service/Cloud/PremiumData/PrecisionAlpha/PrecisionAlphaService.cs
  IEXSharpTest/Cloud/PremiumData/BrainCompanyTest.cs
  IEXSharpTest/Cloud/PremiumData/ExtractAlphaTest.cs
Labels: enhancement
