Repository vslee/IEXSharp, pull requests merged in 2020-04, with the labels that each got.

#9 Fixed multiple V2 Api calls
  IEXSharp/Helper/ExecutorBase.cs
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Helper/ExecutorSSE.cs
  IEXSharp/Model/Shared/Response/Trade.cs
  IEXSharp/Service/V2/Account/AccountService.cs
  IEXSharp/Service/V2/AlternativeData/AlternativeDataService.cs
  IEXSharp/Service/V2/AlternativeData/IAlternativeDataService.cs
  IEXSharp/Service/V2/ForexCurrencies/ForexCurrenciesService.cs
  IEXSharp/Service/V2/Stock/IStockService.cs
  IEXSharp/Service/V2/Stock/StockService.cs
  IEXSharpTest/Cloud(V2)/AccountTest.cs
  IEXSharpTest/Cloud(V2)/StockTest.cs
Labels: bug

#10 Added 'Period' in the QueryString for IncomeStatementAsync
  IEXSharp/Service/V2/Stock/StockService.cs
  IEXSharpTest/Cloud(V2)/StockTest.cs
Labels: bug

#11 Adding ref-data/sectors & ref-data/symbols
  .gitignore
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Model/ReferenceData/Response/SectorResponse.cs
  IEXSharp/Model/ReferenceData/Response/TagResponse.cs
  IEXSharp/Service/V2/ReferenceData/IReferenceDataService.cs
  IEXSharp/Service/V2/ReferenceData/ReferenceDataService.cs
  IEXSharpTest/Cloud(V2)/ReferenceDataTest.cs
Labels: enhancement

#12 Volume By Venue Bugfix
  IEXSharp/Service/V2/Stock/IStockService.cs
  IEXSharp/Service/V2/Stock/StockService.cs
  IEXSharpTest/Cloud(V2)/StockTest.cs
Labels: bug

#13 Adding ref-data/crypto/symbols
  IEXSharp/Model/ReferenceData/Response/SymbolCryptoResponse.cs
  IEXSharp/Service/V2/ReferenceData/IReferenceDataService.cs
  IEXSharp/Service/V2/ReferenceData/ReferenceDataService.cs
  IEXSharpTest/Cloud(V2)/ReferenceDataTest.cs
Labels: enhancement

#14 Added support for Advanced Stats and Technical Indicators
  IEXSharp/Model/Stock/Response/AdvancedStatsResponse.cs
  IEXSharp/Model/Stock/Response/KeyStatsResponse.cs
  IEXSharp/Model/Stock/Response/TechnicalIndicatorResponse.cs
  IEXSharp/Service/V2/Stock/IStockService.cs
  IEXSharp/Service/V2/Stock/StockService.cs
  IEXSharpTest/Cloud(V2)/StockTest.cs
Labels: enhancement

#15 Added support for cryptocurrency price and book
  IEXSharp/IEXCloudClient.cs
  IEXSharp/Model/Crypto/Response/CryptoBookQuote.cs
  IEXSharp/Model/Crypto/Response/CryptoBookResponse.cs
  IEXSharp/Model/Crypto/Response/CryptoPriceResponse.cs
  IEXSharp/Model/Crypto/Response/QuoteCryptoResponse.cs
  IEXSharp/Model/Stock/Response/BatchBySymbolV1Response.cs
  IEXSharp/Service/V2/AlternativeData/IAlternativeDataService.cs
  IEXSharp/Service/V2/Crypto/CryptoService.cs
  IEXSharp/Service/V2/Crypto/ICryptoService.cs
  IEXSharp/Service/V2/SSE/ISSEService.cs
  IEXSharp/Service/V2/SSE/SSEService.cs
  IEXSharpTest/Cloud(V2)/AlternativeDataTest.cs
  IEXSharpTest/Cloud(V2)/CryptoTest.cs
  IEXSharpTest/Cloud(V2)/ForexCurrenciesTest.cs
Labels: enhancement

#17 Adding additional Forex/Currencies endpoints
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Model/ForexCurrencies/Response/CurrencyConvertResponse.cs
  IEXSharp/Model/ForexCurrencies/Response/CurrencyHistoricalRateResponse.cs
  IEXSharp/Model/ForexCurrencies/Response/CurrencyRateResponse.cs
  IEXSharp/Service/V2/Crypto/ICryptoService.cs
  IEXSharp/Service/V2/ForexCurrencies/ForexCurrenciesService.cs
  IEXSharp/Service/V2/ForexCurrencies/IForexCurrenciesService.cs
  IEXSharpTest/Cloud(V2)/ForexCurrenciesTest.cs
Labels: enhancement

#18 Reworking ForexCurrencyService to use ExecuteAsync
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Service/V2/ForexCurrencies/ForexCurrenciesService.cs
Labels: maintenance

#19 Added support for Corporate Actions
  IEXSharp/Helper/EnumExtension.cs
  IEXSharp/Helper/ExecutorREST.cs
  IEXSharp/Model/CoprorateActions/Request/TimeSeriesRange.cs
  IEXSharp/Model/CoprorateActions/Response/AdvancedDividendResponse.cs
  IEXSharp/Model/CorporateActions/Request/TimeSeriesRange.cs
  IEXSharp/Model/CorporateActions/Response/AdvancedDividendResponse.cs
  IEXSharp/Model/CorporateActions/Response/BonusIssueResponse.cs
  IEXSharp/Model/CorporateActions/Response/CorporateActionResponse.cs
  IEXSharp/Model/CorporateActions/Response/DistributionResponse.cs
  IEXSharp/Model/CorporateActions/Response/ReturnOfCapitalResponse.cs
  IEXSharp/Model/CorporateActions/Response/RightToPurchaseResponse.cs
  IEXSharp/Model/CorporateActions/Response/RightsIssueResponse.cs
  IEXSharp/Model/CorporateActions/Response/SecurityUpdateResponse.cs
  IEXSharp/Model/CorporateActions/Response/SpinOffResponse.cs
  IEXSharp/Model/CorporateActions/Response/SplitsResponse.cs
  IEXSharp/Service/V2/CorporateActions/CorporateActionsService.cs
  IEXSharp/Service/V2/CorporateActions/ICorporateActionsService.cs
  IEXSharpTest/Cloud(V2)/CorporateActionsTest.cs
  IEXSharpTest/Cloud(V2)/ForexCurrenciesTest.cs
  IEXSharpTest/Helper/EnumExtensionTest.cs
Labels: enhancement

#20 Minor package bumps
  IEXSharp/IEXSharp.csproj
  IEXSharpTest/IEXSharpTest.csproj
Labels: maintenance
