Repository vslee/IEXSharp, pull requests merged in 2021-02, with the labels that each got.

#98 Change to nullable to match data
  IEXSharp/Model/CoreData/CorporateActions/Response/AdvancedDividendResponse.cs
Labels: bug

#101 Advanced fundamentals fixes cum upgrades
  IEXSharp/Helper/DateTimeExtensions.cs
  IEXSharp/IEXSharp.csproj
  IEXSharp/Model/Shared/Request/TimeSeries.cs
  IEXSharp/Model/Shared/Request/TimeSeriesPeriod.cs
  IEXSharp/Model/Shared/Request/TimeSeriesRange.cs
  IEXSharp/Service/Cloud/CoreData/StockFundamentals/IStockFundamentalsService.cs
  IEXSharp/Service/Cloud/CoreData/StockFundamentals/StockFundamentalsService.cs
  IEXSharpTest/Cloud/CoreData/StockFundamentalsTest.cs
Labels: enhancement

#103 New required disclaimer
  README.md
Labels: documentation

#104 Updated volume, uVolume and fVolume types to decimal from long.
  IEXSharp/Model/CoreData/StockPrices/Response/HistoricalPriceResponse.cs
Labels: bug

#105 Added Reported financials
  IEXSharp/Model/CoreData/StockFundamentals/Response/ReportedFinancialResponse.cs
  IEXSharp/Model/Shared/Request/Filing.cs
  IEXSharp/Model/Shared/Request/TimeSeries.cs
  IEXSharp/Model/Shared/Response/Financial.cs
  IEXSharp/Service/Cloud/CoreData/StockFundamentals/IStockFundamentalsService.cs
  IEXSharp/Service/Cloud/CoreData/StockFundamentals/StockFundamentalsService.cs
  IEXSharpTest/Cloud/CoreData/StockFundamentalsTest.cs
Labels: enhancement
